"""add_user_details

Revision ID: 6bb99ad9237c
Revises: eb7ce1bf9db5
Create Date: 2025-12-07 22:09:11.086130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb99ad9237c'
down_revision: Union[str, None] = 'eb7ce1bf9db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('detail_address', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'detail_address')
    op.drop_column('users', 'address')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
